#!/bin/sh

if [ $# -lt 1 ]; then
	echo "${0##*/}: requires an argument" 1>&2
	exit 1
fi

export STHKD=$$

tmp="$(mktemp -d)"
mkfifo "$tmp/cmd"
chmod 700 "$tmp/cmd"

# since itty prints to stderr, we'll just send this to stdout and let
# the end user handle the rest
cat "$tmp/cmd" & cat=$!

config="$1"; shift
# we're redirecting non-matching input to stdout
itty "$@" bmac -o "$tmp/cmd" -n /dev/stdout "$config"
kill "$cat"

rm -rf "$tmp"
