#!/bin/sh
tmp="$(mktemp -d)"
mkfifo "$tmp/cmd"
chmod 700 "$tmp/cmd"

sh "$tmp/cmd" 1>/dev/null 2>&1 &

# $1 is our config
# we're redirecting non-matching input to stdout
itty bmac -o "$tmp/cmd" -n /dev/stdout "$1"

rm -rf "$tmp"
